[workspace]

members = [
    "zokrates_common",
    "zokrates_core",
    "zokrates_cli",
    "zokrates_fs_resolver",
    "zokrates_stdlib",
    "zokrates_embed",
    "zokrates_abi",
    "zokrates_test",
    "zokrates_core_test",
]

exclude = ["zokrates_js"]
