[package]
name = "zokrates_parser"
version = "0.3.5"
authors = ["JacobEberhardt <jacob.eberhardt@tu-berlin.de>"]
edition = "2018"

[dependencies]
pest = "=2.3"
pest_derive = "2.0"

[dev-dependencies]
glob = "0.2"
