[package]
name = "zokrates_core"
version = "0.4.3"
authors = ["Jacob Eberhardt <jacob.eberhardt@tu-berlin.de>", "Dennis Kuhnert <mail@kyroy.com>"]
repository = "https://github.com/JacobEberhardt/ZoKrates"
readme = "README.md"
build = "build.rs"

[features]
default = ["bellman_ce/nolog"]
libsnark = ["cc", "cmake", "git2"]
wasm = ["bellman_ce/wasm"]
multicore = ["bellman_ce/multicore"]

[dependencies]
num = {version = "0.1.36", default-features = false}
lazy_static = "1.4"
typed-arena = "1.4.1"
reduce = "0.1.1"
# serialization and deserialization
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_bytes = "0.10"
bincode = "0.8.0"
hex = "0.4.2"
regex = "0.2"
pairing_ce = "^0.21"
ff_ce = "^0.9"
zokrates_field = { version = "0.3.0", path = "../zokrates_field" }
zokrates_pest_ast = { version = "0.1.0", path = "../zokrates_pest_ast" }
zokrates_common = { path = "../zokrates_common" }
rand = "0.4"
csv = "1"
bellman_ce = { version = "^0.3", default-features = false }

[dependencies.num-bigint]
version = "0.2"
features = ["serde"]

[dev-dependencies]
glob = "0.2.11"
assert_cli = "0.5"
wasm-bindgen-test = "0.3.0"
pretty_assertions = "0.6.1"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"], optional = true }
cmake = { version = "0.1.31", optional = true }
git2 = { version = "0.13.1", optional = true }
