[package]
name = "zokrates_core"
version = "0.3.2"
authors = ["Jacob Eberhardt <jacob.eberhardt@tu-berlin.de>", "Dennis Kuhnert <mail@kyroy.com>"]
repository = "https://github.com/JacobEberhardt/ZoKrates"
readme = "README.md"
build = "build.rs"

[features]
default = []
libsnark = []

[dependencies]
libc = "0.2.0"
num = {version = "0.1.36", default-features = false}
num-bigint = {version = "0.1.36", default-features = false}
lazy_static = "0.1.*"
reduce = "0.1.1"
# serialization and deserialization
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
bincode = "0.8.0"
regex = "0.2"
bimap = "0.1"
bellman = { git = "https://github.com/matterinc/bellman" }
pairing = { git = "https://github.com/matterinc/pairing" }
ff = { version = "0.4", features = ["derive"] }
rand = "0.4"

[dev-dependencies]
glob = "0.2.11"
assert_cli = "0.5"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
cmake = "0.1.31"