[package]
name = "zokrates_core"
version = "0.3.4"
authors = ["Jacob Eberhardt <jacob.eberhardt@tu-berlin.de>", "Dennis Kuhnert <mail@kyroy.com>"]
repository = "https://github.com/JacobEberhardt/ZoKrates"
readme = "README.md"
build = "build.rs"

[features]
default = []
libsnark = []
wasm = []

[dependencies]
libc = "0.2.0"
num = {version = "0.1.36", default-features = false}
num-bigint = {version = "0.1.36", default-features = false}
lazy_static = "0.1.*"
reduce = "0.1.1"
# serialization and deserialization
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_bytes = "0.10"
bincode = "0.8.0"
regex = "0.2"
bimap = "0.1"
zokrates_field = { version = "0.3.0", path = "../zokrates_field" }
wasmi = "0.4.2"
parity-wasm = "0.35.3"
rustc-hex = "1.0"

[dev-dependencies]
glob = "0.2.11"
assert_cli = "0.5"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
cmake = "0.1.31"
parity-wasm = "0.35.3"
