[package]
name = "zokrates_field"
version = "0.3.5"
authors = ["Thibaut Schaeffer <thibaut@schaeff.fr>", "Guillaume Ballet <gballet@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.4"
bincode = "0.8.0"
serde_json = "1.0"
num-traits = { version = "0.2", default-features = false }
num-integer = { version = "0.1", default-features = false }
pairing_ce = "0.18"
ff_ce = { features = ["derive"], version = "0.7" }

[dev-dependencies]
rand = "0.4"

[dependencies.num-bigint]
version = "0.2"
features = ["serde"]
