[package]
name = "zokrates_field"
version = "0.3.0"
authors = ["Guillaume Ballet <gballet@gmail.com>"]
edition = "2018"

[dependencies]

serde = "1.0"
serde_derive = "1.0"
lazy_static = "0.1.*"
num = {version = "0.1.36", default-features = false}
num-bigint = {version = "0.1.36", default-features = false}
bincode = "0.8.0"