[package]
name = "zokrates_fs_resolver"
version = "0.4.0"
authors = ["Thibaut Schaeffer <thibaut@schaeff.fr>"]
repository = "https://github.com/JacobEberhardt/ZoKrates.git"

[features]
default = []

[dependencies]

[dev-dependencies]
tempfile = "3"

[lib]