[package]
name = "zokrates_fs_resolver"
version = "0.5.1"
authors = ["Thibaut Schaeffer <thibaut@schaeff.fr>"]
repository = "https://github.com/JacobEberhardt/ZoKrates.git"
edition = "2018"

[dependencies]
zokrates_common = { path = "../zokrates_common" }

[dev-dependencies]
tempfile = "3"