name:                           GitHub Package Repo Docker Image

on:
  push:
    branches:
      - 'eyblockchain'

jobs:
  make-gpr-docker-image:
    name:                       Image Release
    runs-on:                    ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build container image
        uses: mr-smithers-excellent/docker-build-push@v3
        with:
         image: zokrates-zexe/zokrates_zexe
         dockerfile: ey.Dockerfile
         tag: ${{ github.sha }}
         registry: docker.pkg.github.com
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
